// export interface Expert {
//     specInfo: {
//         id: number,
//         dateCreated?: string,
//         dateUpdated?: string,
//         licenseNo: string,
//         licenseType: string,
//         grade: string,
//         acceptingCasesType: string,
//         user: {
//           id: number,
//           dateCreated?: string,
//           dateUpdated?: string,
//           phoneNumber:string,
//           type?: string,
//           firstName: string,
//           lastName: string,
//           nationalCode: string,
//           gender: string,
//           placeOfBirth: string,
//           yearOfBirth: number,
//           confirmationStatus: string,
//           isActive?: boolean,
//           about?: string,
//           imageUrl: string,
//           username: string,
//           password: string,
//           roles?:any[],
//         },
//         acceptingProvinces: [
//           {
//             id: number,
//             dateCreated?: string,
//             dateUpdated?: string,
//             title: string,
//             code: number,
//             parent?:object,
//           },
//         ],
//         acceptingWorkScopes:{
//             id: number,
//             dateCreated?: string,
//             dateUpdated?: string,
//             title: string,
//             code: number,
//             parent: object,
//           }[],
//       },
//       contactInfo: {
//         id: number,
//         dateCreated?: string,
//         dateUpdated?: string,
//         province: string,
//         city: string,
//         homeAddress: string,
//         homePostalCode: string,
//         homePhone: string,
//         workAddress: string,
//         workPostalCode: string,
//         workPhone: string,
//         website?: string,
//         email?: string,
//         user?:object
//       },
//       eduDegrees: [
//         {
//           id: 17,
//           dateCreated: null,
//           dateUpdated: null,
//           universityName: "ازاد",
//           grade: "bachelor",
//           fieldOfStudy: "نرمافزار",
//           startingYear: 1390,
//           endYear: 1395,
//           user: {
//             id: 3,
//             dateCreated: "2022-01-17T07:53:38.000+00:00",
//             dateUpdated: "2022-02-21T13:48:01.000+00:00",
//             phoneNumber: "9120382598",
//             type: "expert",
//             firstName: "محمد",
//             lastName: "دریاباری",
//             nationalCode: 1626464985,
//             gender: "male",
//             placeOfBirth: "تهران",
//             yearOfBirth: 1375,
//             confirmationStatus: "notConfirmed",
//             isActive: false,
//             about: null,
//             imageUrl: null,
//             username: "9120382598",
//             password:
//               "$2a$10$N7WqUut4DyMbVh2AmKZFy.hov8FYNTwWI.zfmydY0bpZXJdjS2hkq",
//             roles: [
//               { id: 1, dateCreated: null, dateUpdated: null, title: "ROLE_USER" },
//             ],
//           },
//           fileUrl:
//             "/core/file/download/fileFri Jan 21 2022 22:03:41 GMT+0330 (Iran Standard Time)",
//           latestDegree: false,
//           studying: false,
//         },
//         {
//           id: 23,
//           dateCreated: null,
//           dateUpdated: null,
//           universityName: "rrrrr",
//           grade: "master",
//           fieldOfStudy: "rrrrr",
//           startingYear: 1392,
//           endYear: 1394,
//           user: {
//             id: 3,
//             dateCreated: "2022-01-17T07:53:38.000+00:00",
//             dateUpdated: "2022-02-21T13:48:01.000+00:00",
//             phoneNumber: "9120382598",
//             type: "expert",
//             firstName: "محمد",
//             lastName: "دریاباری",
//             nationalCode: 1626464985,
//             gender: "male",
//             placeOfBirth: "تهران",
//             yearOfBirth: 1375,
//             confirmationStatus: "notConfirmed",
//             isActive: false,
//             about: null,
//             imageUrl: null,
//             username: "9120382598",
//             password:
//               "$2a$10$N7WqUut4DyMbVh2AmKZFy.hov8FYNTwWI.zfmydY0bpZXJdjS2hkq",
//             roles: [
//               { id: 1, dateCreated: null, dateUpdated: null, title: "ROLE_USER" },
//             ],
//           },
//           fileUrl:
//             "/core/file/download/fileFri Jan 21 2022 03:45:29 GMT+0330 (Iran Standard Time)",
//           latestDegree: false,
//           studying: false,
//         },
//         {
//           id: 24,
//           dateCreated: null,
//           dateUpdated: null,
//           universityName: "سشبشسببشبشسبسشبسبش",
//           grade: "phd",
//           fieldOfStudy: "سبسشبشسیشسیشسیشیس",
//           startingYear: 1300,
//           endYear: 1302,
//           user: {
//             id: 3,
//             dateCreated: "2022-01-17T07:53:38.000+00:00",
//             dateUpdated: "2022-02-21T13:48:01.000+00:00",
//             phoneNumber: "9120382598",
//             type: "expert",
//             firstName: "محمد",
//             lastName: "دریاباری",
//             nationalCode: 1626464985,
//             gender: "male",
//             placeOfBirth: "تهران",
//             yearOfBirth: 1375,
//             confirmationStatus: "notConfirmed",
//             isActive: false,
//             about: null,
//             imageUrl: null,
//             username: "9120382598",
//             password:
//               "$2a$10$N7WqUut4DyMbVh2AmKZFy.hov8FYNTwWI.zfmydY0bpZXJdjS2hkq",
//             roles: [
//               { id: 1, dateCreated: null, dateUpdated: null, title: "ROLE_USER" },
//             ],
//           },
//           fileUrl: null,
//           latestDegree: false,
//           studying: true,
//         },
//       ],
//       jobExperiences: [
//         {
//           id: 3,
//           dateCreated: null,
//           dateUpdated: null,
//           instituteName: "موسسه 1",
//           jobPosition: "مدیر",
//           startingYear: 1399,
//           endYear: 1400,
//           user: {
//             id: 3,
//             dateCreated: "2022-01-17T07:53:38.000+00:00",
//             dateUpdated: "2022-02-21T13:48:01.000+00:00",
//             phoneNumber: "9120382598",
//             type: "expert",
//             firstName: "محمد",
//             lastName: "دریاباری",
//             nationalCode: 1626464985,
//             gender: "male",
//             placeOfBirth: "تهران",
//             yearOfBirth: 1375,
//             confirmationStatus: "notConfirmed",
//             isActive: false,
//             about: null,
//             imageUrl: null,
//             username: "9120382598",
//             password:
//               "$2a$10$N7WqUut4DyMbVh2AmKZFy.hov8FYNTwWI.zfmydY0bpZXJdjS2hkq",
//             roles: [
//               { id: 1, dateCreated: null, dateUpdated: null, title: "ROLE_USER" },
//             ],
//           },
//           working: false,
//         },
//         {
//           id: 4,
//           dateCreated: null,
//           dateUpdated: null,
//           instituteName: "موسسه 1",
//           jobPosition: "مدیر",
//           startingYear: 1399,
//           endYear: 1400,
//           user: {
//             id: 3,
//             dateCreated: "2022-01-17T07:53:38.000+00:00",
//             dateUpdated: "2022-02-21T13:48:01.000+00:00",
//             phoneNumber: "9120382598",
//             type: "expert",
//             firstName: "محمد",
//             lastName: "دریاباری",
//             nationalCode: 1626464985,
//             gender: "male",
//             placeOfBirth: "تهران",
//             yearOfBirth: 1375,
//             confirmationStatus: "notConfirmed",
//             isActive: false,
//             about: null,
//             imageUrl: null,
//             username: "9120382598",
//             password:
//               "$2a$10$N7WqUut4DyMbVh2AmKZFy.hov8FYNTwWI.zfmydY0bpZXJdjS2hkq",
//             roles: [
//               { id: 1, dateCreated: null, dateUpdated: null, title: "ROLE_USER" },
//             ],
//           },
//           working: false,
//         },
//         {
//           id: 7,
//           dateCreated: null,
//           dateUpdated: null,
//           instituteName: "یییی",
//           jobPosition: "یییی",
//           startingYear: 1350,
//           endYear: 1400,
//           user: {
//             id: 3,
//             dateCreated: "2022-01-17T07:53:38.000+00:00",
//             dateUpdated: "2022-02-21T13:48:01.000+00:00",
//             phoneNumber: "9120382598",
//             type: "expert",
//             firstName: "محمد",
//             lastName: "دریاباری",
//             nationalCode: 1626464985,
//             gender: "male",
//             placeOfBirth: "تهران",
//             yearOfBirth: 1375,
//             confirmationStatus: "notConfirmed",
//             isActive: false,
//             about: null,
//             imageUrl: null,
//             username: "9120382598",
//             password:
//               "$2a$10$N7WqUut4DyMbVh2AmKZFy.hov8FYNTwWI.zfmydY0bpZXJdjS2hkq",
//             roles: [
//               { id: 1, dateCreated: null, dateUpdated: null, title: "ROLE_USER" },
//             ],
//           },
//           working: false,
//         },
//         {
//           id: 8,
//           dateCreated: null,
//           dateUpdated: null,
//           instituteName: "rrr",
//           jobPosition: "rrr",
//           startingYear: 1352,
//           endYear: 1355,
//           user: {
//             id: 3,
//             dateCreated: "2022-01-17T07:53:38.000+00:00",
//             dateUpdated: "2022-02-21T13:48:01.000+00:00",
//             phoneNumber: "9120382598",
//             type: "expert",
//             firstName: "محمد",
//             lastName: "دریاباری",
//             nationalCode: 1626464985,
//             gender: "male",
//             placeOfBirth: "تهران",
//             yearOfBirth: 1375,
//             confirmationStatus: "notConfirmed",
//             isActive: false,
//             about: null,
//             imageUrl: null,
//             username: "9120382598",
//             password:
//               "$2a$10$N7WqUut4DyMbVh2AmKZFy.hov8FYNTwWI.zfmydY0bpZXJdjS2hkq",
//             roles: [
//               { id: 1, dateCreated: null, dateUpdated: null, title: "ROLE_USER" },
//             ],
//           },
//           working: false,
//         },
//       ],
// }